# Base image
FROM node:14-alpine

RUN apk update
RUN apk add git

# Set environment variables
ENV TABLE_NAME production
ENV PORT 3000

# Copy app files and install dependencies
COPY . /app
WORKDIR /app
RUN npm install

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
